dist: xenial
sudo: require
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - kalakris-cmake
    packages:
    - g++-6
    - clang-3.8
    - cmake
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - cmake --config Debug .
  - cmake --build .
  - ./test/Debug/IonIrTests
notifications:
  email: false
