dist: cosmic
sudo: require
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - cmake
    - clang-8
script:
  - sudo apt-get install -y libc++1 libc++abi1
  - sudo apt-get --purge remove -y llvm
  - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-8 g++-8
  - sudo rm /usr/bin/g++
  - sudo ln /usr/bin/g++-8 /usr/bin/g++
  - sudo apt-get install -y libedit-dev
  - cmake --config Debug .
  - cmake --build .
  - ./test/IonIrTests
notifications:
  email: false
