dist: xenial
sudo: require
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    - kalakris-cmake
    packages:
    - g++-6
    - clang-3.8
    - cmake
install:
- "[ $CXX = g++ ] && export CXX=g++-6 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 8
  - cmake --config .
  - cmake --build .
  - ./test/IonIrTests
notifications:
  email: false
