dist: cosmic
sudo: require
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - cmake
    - clang-8
script:
  - sudo apt-get install -y libc++1 libc++abi1
  - sudo apt-get --purge remove -y llvm
  - wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 9
  - cmake --config Debug .
  - cmake --build .
  - ./test/IonIrTests
notifications:
  email: false
