version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Update packages
          command: "apt-get update"

      - run:
          name: Install SUDO
          command: "apt-get install -y sudo && rm -rf /var/lib/apt/lists/*"

      - run:
          name: Install GCC
          command: "sudo apt-get install -y gcc g++"

      - run:
          name: Install CMake
          command: "sudo apt-get install -y cmake"

      - run:
          name: Configure project
          command: "cmake --config Debug ."

      - run:
          name: Build project
          command: "cmake --build ."

      - run:
          name: Run tests
          command: "./test/Debug/IonIrTests"
